package com.chimanos.chucknorris.fact.model;

import java.util.Arrays;
import java.util.List;

public class Constants {

    public static final List<String> FACTS = Arrays.asList(
            "quand chuck norris fait l'épreuve des araignées dans fort boyard, elles sortent elles-mêmes les petits papiers et lisent à voix haute ",
            "chuck norris peut faire des ronds avec une equerre ",
            "chuck norris peut écrire un traitement de texte avec la souris ",
            "peter parker a été mordu par une araignée, clark kent a été mordu par chuck norris ",
            "chuck norris se souvient très bien de son futur ",
            "chuck norris peut dire schwarzkopf en verlan ",
            "rien ne sert de jouer aux échecs avec chuck norris, il ne connait pas l'échec ",
            "chuck norris ne prends jamais de laxatif; personne ne fait chier chuck norris",
            "le papier wc de chuck norris n'a pas de fin chuck norris n'est jamais au bout du rouleau ",
            "chuck norris a gagné la guerre du golf, entrous ",
            "les portraits de chuck norris ne sont pas a vendre on ne se paie pas la tête de chuck norris ",
            "l'ordinateur de chuck norris n'a pas de bouton crtl chuck norris a toujours le contrôle ",
            "chuck norris a deja reussi a casserpattes a un canard ",
            "en avril dernier, chuk norris a fait un barbecue et les aéroports européens ont été fermés pendant une semaine ",
            "depuis leseptembrechuck norris ne lance plus d'avions en papier ",
            "le nombre de choses impossibles pour chuck norris est inférieur à zéro ",
            "un jour, chuck norris a plongé dans la mer rouge moïse en a profité pour passer ",
            "quand chuck norris dit qu'il a inventé les ricolasles suisses ferment leurs gueules ",
            "mpropre était videur et ne voulait pas laisser chuck rentrer en boite, maintenant il est femme de ménage",
            "chuck norris mange ses oranges tout rond: chuck norris fait pas de quartier ",
            "chuck norris a déjà tabassé l homme invisible parce qu il lui gâchait la vue ",
            "chuck norris ne s'est jamais rendu à l'écolechuck norris ne se rend jamais",
            "quand chuck norris va au mcdo, les hamburgers sont aussi bien que sur les photos, même mieux ",
            "chuck norris regarde charlie chaplin avec le son ",
            "chuck norris ne ment jamais, c'est la vérité qui se trompe ",
            "chuck norris ne fume pas car la santé de chuck norris est dangereuse pour le tabac ",
            "chuck norris a joué au roi du silence avec un muet et il a gagné ",
            "chuck norris peut faire des chateaux de kart ",
            "chuck norris a été conçu en mode sans echecs ",
            "quand chuck norris regarde le soleil c'est le soleil qui a mal aux yeux ",
            "chuck norris peut te faire passer un sale quart d'heure ensecondes, dialogues et génériques inclus ",
            "quand chuck norris fait du saut à l'élastique, il saute sans élastique on ne retient pas chuck norris ",
            "chuck norris peut cultiver un champ magnétique ",
            "chuck norris à réussi à trouver la page",
            "le poisson rouge de chuck norris habite dans le loch ness ",
            "chuck norris peut faire un solo de heavy metal avec un ukulélé ",
            "quand un gendarme dit papiers à chuck norris et que celui-ci répond ciseaux, il a effectivement gagné ",
            "chuck norris peut appuyer sur ctrl-alt-suppr avec une seule main ",
            "chuck noriss peut faire du feu en frottant deux glaçons ",
            "chuck norris peut jouer à world of warcraft sur game boy color ",
            "lorsque chuck norris fait de la plongée, il ne prend jamais de tuba on entube pas chuck norris ",
            "tout les soir les cauchemars font le même chuck norris ",
            "hercule avait le choix : combattre chuck norris ou descendre aux enfersheureusement, hercule a été raisonnable ",
            "chuck norris peut dessiner un triangle àangles obtus ",
            "lorsque vous discutez avec chuck norris sur msn, le raccourci alt+f ne marche pas, tout comme le bouton power de votre pc d'ailleurson n'echap pas à chuck norris ",
            "lorsque chuck norris voit une étoile fillante,celle-ci fait un voeux ",
            "quand chuck norris dit à obelix qu'il est gros, obelix est d'accord ",
            "chuck norris connait le nom du soldat inconnu ",
            "chuck norris n'apprend pas, il se souvient ",
            "quand chuck norris se regarde dans une petite cuillére son image est renvoyé à l'endroit",
            "chuck norris n'est pas le meilleur, car, pour pouvoir être le meilleur, il faut d'abord pouvoir être comparable ",
            "chuck norris peut éteindre un feu de foret avec un tourne-vis accessoirement, il peut aussi visser une vis avec un extincteur",
            "un jour, au restaurant, chuck norris a commandé un steak et le steak a obéi ",
            "si chuck norris avait été pris dans le filmil l'aurait renommé en",
            "dans une pièce normale, il y a en moyenneobjets avec lesquels chuck norris peut vous tuer, en incluant la pièce elle même ",
            "chuck norris est le père de schtroumpfette ",
            "la guerre du golfe a commencé quand chuck norris a raté le ème trou ",
            "chuck norris connait la dernière décimale de pi ",
            "chuck norris mesure son pouls sur l'échelle de richter ",
            "chuck norris peut encercler ses ennemis tout seul ",
            "chuck norris peut ouvrir un pdf avec un couteau ",
            "chuck norris sait où se cache ben laden, il a juste pas fini de compter ",
            "un jour un tigre à bousculé chuck norrisc'est là que le chat est né ",
            "chuck norris peut se toucher le coude gauche avec la main gauche ",
            "chuck norris a appris à nager dans l'océan militaire maintenant il est pacifique ",
            "chuck norris peut faire du motocross avec un camion poubelle ",
            "le prochain james bond s'intitulera : rien que pour chuck norris ",
            "si chuck norris avait joué dans star wars il n'y aurait eu qu'une seule trilogie ",
            "chuck norris peut faire une reprise de volée au handball ",
            "tu révises mais ça ne veut pas rentrer dans ta tête ? chuck norris peut t'aider",
            "chuck norris a inventé le livre sur comment lire et ça marche ",
            "chuck norris est tellement intelligent qu'il utilise ses trois hémisphères cérébraux ",
            "chuck norris est le seul homme au monde à ne pas connaître la blague de la bougie d'anniversaire qui se rallume personne n'a osé ",
            "un matin le lapin de chuck norris a tué un chasseur mais un chasseur f- ",
            "même avec des ampoules aux pieds, chuck norris frappe plus vite que la lumière ",
            "quand le soleil se couche, c'est chuck norris qui le borde ",
            "quand chuck norris mange des chips, il entend quand même la télé ",
            "l'instit de chuck norris ne l'a jamais mis au coin lui par contre l'a déjà mis au tapis ",
            "chuck norris est déjà allé à perpette ",
            "chuck norris peut mettre des roundhouse kick dans pac-man ",
            "conan appelle chuck norris crom pour ne pas l'offenser ",
            "le jour où nietzsche a écrit dieu est mort, c'était vrai il l'avait vu fallait pas provoquer chuck norris ",
            "chuck norris connait la blague du con qui dit non, et c'est pas lui ",
            "chuck norris est contre la cigarette, car elle tue presque autant que lui ",
            "quand chuck norris était enfant, il avait un iphone ",
            "chuck norris encaisse les coups dans son compte en banque ",
            "quand chuck norris plante sur irc, tout le monde l'attend pour reprendre la parole ",
            "c'est chuck norris qui a présenté son père à sa mère ",
            "chuck norris ne fait pas d'omelette sans casser les crânes ",
            "c'est en poussant le continent américain à la nage que chuck norris a découvert le bateau de christophe colomb ",
            "chuck norris ne rate jamais la poubelle ",
            "l'homme élastique est le chewing gum de chuck norris ",
            "c'est chuck norris qui a montré aux poissons comment nager ",
            "chuck norris n'est pas allé a l'école, il savait déja tout ",
            "c'est pas parce que tu es encore en vie que ça veut forcément dire que chuck norris t'aime bien ",
            "c'est chuck norris qui sauve l'airbag dans un accident ",
            "chuck norris joue au foot avec un ballon d'eau chaude ",
            "chuck norris mange aussi les coquilles des huitres c'est plus croquant ",
            "qu'est ce qu'une lada au sommet d'une montagne?un miracle?non, c'est chuck norris qui était au volant ",
            "chuck norris déteste les requins, ils le chatouillent quand il se baigne ",
            "chuck norris est plus baraque qu'obama ",
            "chuck norris coule réellement un bronze quand il fait la grosse commission ",
            "la constellation de chuck norris se trouve sur holywood boulevard ",
            "adriana karembeu ne peut pas regarder chuck norris dans les yeux ",
            "chuck norris arrive a traire une vache sans la toucher ",
            "si chuck norris avait été sur le titanic, c'est l'iceberg qui aurait coulé ",
            "quand chuck norris parle le silence se tait ",
            "le prix du pétrole augmente pour rembourser chuck norris ",
            "quand chuck norris paye en ticket restaurant on lui rend la monnaie ",
            "chuck norris fait des combats de sabre laser à mains nues ",
            "chuck norris peut retourner un glaçon ",
            "chuck norris peut parler dans un film muet ",
            "chuck norris peut faire du toboggan debout ",
            "chuck norris peut couper un cheveu en quatre avec une scie ",
            "chuck norris n'a aucun synonyme ",
            "la télécommunication n'existe pas, chuck norris poste les mails ",
            "chuck norris ne vieillit pas il fait semblant ",
            "chuck norris peut battre ses ennemis par téléphone ",
            "au démineur, si chuck norris clique sur une case qui se trouve autour d'un , il n'y a pas de bombe ",
            "les émeraudes du chaos de sonic sont en fait des galets provenant de l'allée du jardin de chuck norris ",
            "chuck norris peut rouler sur l'autoroute les fenêtres ouvertes sans que ça fasse de bruit ",
            "chuck norris fait aussi le m en ', mais à la nage ",
            "au cinéma chuck norris n'a pas de doublure ",
            "les règles d'accord du participe passé ne s'appliquent pas à chuck norris ",
            "chuck norris mange de la kryptonite en salade ",
            "chuck norris peut résoudre tous les rubik's cube en un seul mouvement ",
            "chuck norris lit l'avenir dans les cartes routières ",
            "chuck norris a déjà retenu sa respiration pendantheures : le temps que ça lui a pris pour boucher le trou dans la station orbitale ",
            "quand chuck norris envoie un sms pour souhaiter la bonne année, il passe du premier coup ",
            "on ne voit pas chuck norris, on le ressent, surtout son pied ",
            "quand chuck norris va chez le médecin, la sécurité sociale rembourse le medecin ",
            "quand chuck norris est flashé au radar, il peut payer en amandes ",
            "chuck norris, c'est comme un pot de ricorée posé à l'envers sur la table du jardin un dimanche matin ensoleillé, mais avec du red bull en plus ",
            "ne demandez jamais à chuck norris de descendre le chien ",
            "avoir une photo de chuck norris sur soi pendant une épreuve sportive est considéré comme du dopage ",
            "chuck norris a déja converti des végétariens au cannibalisme ",
            "chuck norris n'a pas de numéro de sécu il n'est jamais malade ",
            "chuck norris fait des pompes rien qu'avec son souffle",
            "chuck norris sait faire des claquettes pieds nus ",
            "quand chuck norris fait du vélo, il pédale si vite que la roue arrière double la roue avant ",
            "le matériau le plus solide au monde n'est pas le diamant mais le poing de chuck norris ",
            "jacques audiard a décidé de tourner de battre mon coeur s'est arrété le jour où chuck norris a tourné une scène à quelques metres de lui ",
            "le frigo de chuck norris peut vraiment résister à une explosion nucléaire ",
            "chuck norris peut faire sauter ses pv son record actuel est de m de haut ",
            "dans la série death note, kira voulait s'appeler chuck norris mais c'était déjà pris ",
            "si terminator dit qu'il va revenir, c'est pour avoir un autographe de chuck norris ",
            "chuck norris sait faire la roue sur un doigt ",
            "chuck norris ne voyage pas, c'est le pays qui vient à lui ",
            "chuck norris a donné un doigt à et ",
            "chuck norris gère sa pousée de cheveux ",
            "chuck norris boit de l'eau avec des baguettes ",
            "ben laden n'a pas disparu, il est juste empaillé sur la cheminée de chuck norris ",
            "chuck norris et ça repart (ou pas) ",
            "chuck norris finit ses choux de bruxelles et se ressert ",
            "quand chuck norris appelle monica belluci, elle vient ",
            "chuck norris a enseigné l'art du camouflage aux caméléons ",
            "chuck norris a un seul tour dans son sac, et ça lui suffit ",
            "chuck norris n'aime pas ce site il déteste qu'on le dévalorise ",
            "chuck norris comprend les blagues du télé z ",
            "quand chuck norris laisse les fenêtres ouvertes et les lumières allumées, les moustiques ne rentrent pas ",
            "devant chuck norris, une équation mathématique se résout seule on ne fait pas perdre son temps à chuck norris ",
            "chuck norris a inventé l'expressionfriter quelqu'unen allant au mcdo ",
            "chuck norris a une carte de donneur d'orgasme ",
            "quand chuck norris remplace solid snake, les gardes préfèrent faire semblant de ne pas le voir ",
            "chuck norris a vraiment mis un tigre dans le moteur de son pick-up ",
            "chuck norris peut ouvrir la fenêtre en tgv ",
            "chuck norris peut tuer n'importe qui avec un jouetàans ",
            "dans le verre de bière de chuck norris, la mousse est en-dessous ",
            "quand chuck norris entre dans un café , il ne fait pas plouf ",
            "ne soutenant pas la comparaison avec chuck norris, dieu decida d'inventer le pantalon ",
            "les neveux et nièces de chuck norris ne le forcent pas a regarder dora l'exploratrice ",
            "un jour quelqu'un a ditce n'est pas la mer à boirechuck norris a répondu heureusement ça serait trop facile ",
            "quand chuck norris fait des casse-tête chinois, il ne vaut mieux pas être le chinois ",
            "arsène lupin a du brutalement arrêté sa carrière après avoir tenté de cambrioler chuck norris ",
            "chuck norris ne descend pas du singe il descend, point barre ",
            "quand yoda parle de la force, il parle de chuck norris ",
            "le ballon de rugby fut inventé lorsque chuck norris frappa dans un ballon de foot ",
            "l'ordinateur idéal est aussi puissant que chuck norris ",
            "will smith a du rebaptiser son dernier film je suis une sous-merde, pour ne pas confondre avec le film autobiographique de chuck norris ",
            "chuck norris est le seul homme à avoirgroupes sanguins dans le corps ",
            "quand chuck norris dit stop, le temps s'arrête ",
            "chuck norris peut cocher lesur une grille du loto ",
            "un jour chuck norris a tenté le grand écard depuis les continents dérivent ",
            "quand chuck norris va chez l'hypnotiseur, c'est l'hypnotiseur qui s'endort ",
            "chuck norris a déjà battu la montre dans une course contre la montre ",
            "chuck norris joue au foot avec les comètes ",
            "si chuck norris avait joué james bond, son nom de code n'aurait pas étémais",
            "chuck norris a connu la défaite, et il lui a éclatée la gueule ",
            "chuck norris pêche le poisson déjà pané ",
            "quand on cherche chuck norris, c'est toujours la mort qu'on trouve ",
            "chuck norris a déjà traversé le pacifique, en apnée ",
            "chuck norris n'a pas pu participer à secret story car ce n'est un secret pour personne que chuck norris gagne toujours ",
            "les héros de lost ont eu de la chance, ils auraient pu s'écraser dans le jardin de chuck norris ",
            "c'est chuck norris qui a appris a james bond comment ne pas ressentir les décalage horaires ",
            "chuck norris peut se cacher dans une pièce vide ",
            "quand chuck norris achète des actions en bourse, celles-ci voient leur cours monter immédiatement ",
            "chuck norris peut tracer une règle avec un trait ",
            "chuck norris sait parler le langage binaire ",
            "quand chuck norris creuse un trou, on peut voir le ciel ",
            "les lunettes d servent à avoir les mêmes sensations que chuck norris quand il va au cinéma ",
            "chuck norris n'a jamais perdu en jouant à pile ou face : la pièce ne retombe pas ",
            "chuck norris a le pouvoir de déshabiller les femmes par la pensée mais n'a jamais eu à s'en servir",
            "les requins aiment porter des dents de chuck norris en résine ",
            "chuck norris c'est un peu comme dieu, mais en mieux ",
            "chuck norris secoue ses victimes avant de les tuer sinon la pulpe reste en bas ",
            "chuck norris sait parler le verlan en chinois ",
            "chuck norris n'a jamais eu d'accident de voiture du moins, il n'a jamais rien senti ",
            "chuck norris dispose d'un joueur pour tirer les corners au babyfoot ",
            "avant de rencontrer chuck norris, oui-oui s'appelait non-non ",
            "si chuck norris avait vécu au e siècle, personne aujourd'hui ne saurait qui était casanova ",
            "on dit qu'il faut cueillir les cerises avec la queue on dit aussi que seul chuck norris y parvient ",
            "chuck norris n'a pas besoin de cartes pour te battre à magic ",
            "sur la session msn de chuck norris, il y a une option tuer le contact ",
            "quand adam se cachait le sexe avec une feuille de vigne, chuck norris utilsait un arbre ",
            "les dentifrices deviennent plus blancs quand on les frotte sur les dents de chuck norris ",
            "chuck norris peut te prouver que la condamnation à mort n'est pas la peine maximale ",
            "chuck norris a déjà cassé les dents d'une poule ",
            "quand chuck norris à libéré ingrid, il pensait tourner le numérode walker texas rangers ",
            "chuck norris cache lui même ses oeufs de paques, sinon c'est trop facile ",
            "quand chuck norris mange une orange il n'enlève pas la peaunormal, chuck ne fait pas de quartier ",
            "si chuck norris se fait transpercer par un sabre laser, le sabre laser se casse",
            "le yéti à vu chuck norris, c'est pour cela qu'on ne le voit plus ",
            "c'est chuck norris qui lance les avions depuis les porte-avions ",
            "si on loue le seigneur, c'est parce que chuck norris est hors de prix ",
            "le jour de sa naissance, c'est chuck norris qui tapait sur les fesses des sages-femmes ",
            "chuck norris peut reconstituer une vache entière à partir de steacks hachés ",
            "quand chuck norris s'est mis aux arts martiaux, les japonais se sont reconvertis dans les jeux videos ",
            "le truman show est un documentaire expliquant comment chuck norris nous fait vivre dans un monde qu'il a créé ",
            "united colors of chuck norris ",
            "chuck norris s'est opéré lui même des amygdales ",
            "quand chuck norris viole la loi, elle a mal ",
            "chuck norris a inspiré bruce tout puissant ",
            "quand chuck norris joue au poker, même le soleil se couche ",
            "chuck norris n'a jamais été puceau ",
            "la couleur pourpre de spielberg est inspiré de la magnifique teinte de cheveux de chuck norris ",
            "chuck norris peut téléphoner avec une banane ",
            "une légende raconte qu'un homme aurait déjà vu chuck norris cligner des yeux ",
            "les ondes du cerveau de chuck norris sont dangereuses pour les téléphones portables ",
            "pendant les manifestations, chuck norris casse du casseur ",
            "quand chuck norris surfe sur internet, il faut s'attendre au pire to pire ",
            "chuck norris est capable de faire un homerun au baby foot ",
            "chuck norris dit aux videurs s'ils peuvent rester ou non devant leur discothèque ",
            "pourquoi la vache qui rit, rit ? parce que chuck norris lui a interdit de pleurer ",
            "après avoir descendu les poubelles, chuck norris n'oublie pas d'en faire de-même avec les éboueurs ",
            "c'est chuck norris qui a mis la terre en orbite ",
            "quand chuck norris joue à un first person shoot en d, les ennemis finissent vite en d ",
            "chuck norris n'a pas de volets, le soleil ne se lève pas avant chuck norris ",
            "un jour chuck norris a frappé cindy sanders, elle a vu des papillon de lumière ",
            "ce ne sont pas les parents de chuck norris qui ont choisi d'avoir un enfant, c'est chuck qui a choisi d'avoir des parents ",
            "quand chuck norris part en vacances en camargue, les moustiques disparaissent ",
            "la vénus de milo mangeait trop de chocolat, ça a finit par gonfler chuck norris ",
            "quand les musclés ont vu des photos de chuck norris, ils ont compris qu'il valait mieux qu'ils se séparent ",
            "quand chuck norris mange un hamburger les tranches de tomates reste à l'intérieur ",
            "le calendrier maya s'arrête le jour de la mort de chuck norris ",
            "chuck norris n'aime pas les radars, ça l'éblouit quand il fait du skate ",
            "c'est chuck norris qui pédalait sur le vélo dans et ",
            "toute personne qui prononce chuck norris à voix haute perdminutes de sa vie ",
            "zeus est un grand dragueur , mais il ne ferait pas l'erreur de draguer la femme de chuck norris ",
            "quand chuck norris utilise un parfum, on entend toujours la musique d'ambiance qui va avec ",
            "l'armée des etats unis ne compte qu'un seul homme nommé chuck norris ",
            "lorsque chuck norris découvrit les sushis, on décida de sauver willy ",
            "chuck norris peut placer le mot idoine dans n'importe quelle phrase ",
            "seul chuck norris sait écrire à la plume alors qu'elle est encore sur le volatile",
            "quand chuch norris part en randonnée, les marmottes portent ses affaires ",
            "on ne dit pas ma maitresse d'école mais ma maitresse a eu une altercation avec chuck norris ",
            "chuck norris a inventé le dictionnaire en écrivant sa liste de courses ",
            "wii fit à du mal à suivre chuck norris ",
            "chuck norris peut attraper mario avec une pokéball ",
            "si tu fais un croche-patte à chuck norris, c'est toi qui tombe ",
            "aucun commerçant n'a jamais osé refuser un billet deeuro de chuck norris ",
            "robocop est le jouet préféré de chuck norris ",
            "donner à chuck norris, c'est donné, reprendre, c'est crever ",
            "sur la tombe de chuck norris, on écrira : actuellement en arrêt maladie ",
            "chuck norris comprend ceux qui mettent le gilet jaune autour du siège ",
            "un jour chuck norris a dit lève toi et marcheet l'homme devînt bipède ",
            "si chuck norris n'a jamais tourné film x, c'est parce que les caméras ne sont pas encore assez large pour ça ",
            "si il y a des continents dans le monde, c'est parce que chuck norris a organisé son potager ",
            "chuck norris a battu sherlock holmes au cluedo ",
            "chuck norris doit respirer de l'hélium pour imiter la voix de barry white ",
            "chuck norris n'a besoin que detouches pour se servir d'un ordinateur :et",
            "c'est chuck norris qui a expliqué à sa mère comment faire les bébés ",
            "c'est chuck norris qui a inventé la fracture ",
            "chuck norris a accès à tout internet en chine ",
            "le premier job d'été de chuck norris fut chirurgien on ne donne pas de boulots minables à chuck norris ",
            "chuck norris ne cherche jamais la petite bête, il l'écrase ",
            "chuck norris peut faire un ko en boxant contre son ombre ",
            "chuck norris a arreté l'école àans avec un doctorat en philosophie ",
            "quand chuck norris a trop chaud, il mange un frigo ",
            "chuck norris a fait la blague j'ai piqué ton nez au sphinx ",
            "le japon est le plongeoir de chuck norris ",
            "chuck norris souffle sur sa soupe pour la réchauffer ",
            "les illusions d'optique croient que chuck norris les regarde ",
            "chuck norris sait chronométrer plus vite que n'importe quel chronomètre ",
            "c'est chuck norris qui a fait disparaitre le cercle des poètes ",
            "si les stars de cinema peuvent pleurer aussi facilement, c'est parce qu'elles ont vu chuck norris ",
            "si chuck norris se casse une dent , elle repousse",
            "seul le point du i à le droit d'être au dessus de chuck norris ",
            "chuck norris a des gouts très simples : il se contente du meilleur ",
            "a limage des clochettes pour chat, chuck norris a cru bon de doter certains serpents de sonnettes ",
            "quand la chine s'éveillera, le monde tremblerasauf chuck norris ",
            "quand chuck norris embrasse une grenouille, elle se transforme en strip-teaseuse ",
            "chuck norris ne fait pas de fitness, son physique est naturellement parfait ",
            "chuck norris a installé une nouvelle alarme chez lui pour prévenir les voleurs de son retour ",
            "quand chuck norris caresse un chien, il ronronne ",
            "quand chuck norris marche dans la merde du pied gauche, ça porte malchance au propriétaire du chien ",
            "chuck norris trouve les vélib trop lourds, il a du mal à dépasser sur l'autoroute ",
            "chuck norris n'a jamais été piégé par une caméra cachée rien n'est caché aux yeux de chuck norris ",
            "un soir le marchant de sable a tenté d'endormir chuck norris, en vain ainsi naquit la dune du pyla ",
            "chuck norris recharge son mp en branchant les écouteurs à ses oreilles ",
            "lorsque peter pan veut s'envoler, il pense a chuck norris ",
            "l'incroyable hulk est l'animal de compagnie de chuck norris ",
            "l'homme propose, la femme dispose et chuck norris impose ",
            "chuck norris a terminé tous les tomb raider en utilisant uniquement les seins de lara croft ",
            "lors de la communion, on boit le sang du christ et on mange sa chair en hommage à chuck norris ",
            "quand chuck norris contemple le mont rushmore, les visages baissent les yeux ",
            "chuck norris a noyé archimède dans sa baignoire ",
            "quand chuck norris joue à sonic , tails ne meurt pas ",
            "chuck norris a déjà gagné une partie d'échecs avec un carré d'as ",
            "les mines se désamorcent d'elles-mêmes lorsque chuck norris pose le pied dessus ",
            "chuck norris peut avoir des fleurs en plantant windows ",
            "c'est quand chuck norris s'est assis sur un dromadaire qu'est né le chameau ",
            "personne n'ose faire de prise de sang à l'épouse de chuck norris on ne pique pas la femme de chuck norris",
            "si chuck norris avait une fille, elle aurait quand même des couilles ",
            "un jour chuck norris a mangé du lion vraiment ",
            "chuck norris a déjà fini second life ",
            "dans le chant des partisans, l'ami est évidemment chuck norris ",
            "le proverbe favori de chuck norris est des coups et des douleurs, on ne doit pas discuter ",
            "c'est chuck norris qui a attaché cerbere aux portes de l'enfer ",
            "chuck norris préfère les pommes de terres on ne carotte pas chuck norris ",
            "chuck norris est devenu orphelin le jour où ses parents lui ont interdit de jouer avec son nounours teddy ",
            "bouddha ne pardonne qu'une fois dommage chuck norris ne pardonne pas ",
            "quand chuck norris prend la voiture, les panneaux stop disparaissent on ne peut pas stopper chuck norris ",
            "les hommes en chaise roulante courent lorsqu'ils aperçoivent chuck norris ",
            "chuck norris peut se vanter de sa modestie ",
            "chuck norris mange un bol de kryptonite tous les matins il trouve ça bon ",
            "chuck norris a connu les dinosaures il n'en existe malheureusement plus un pour le confirmer ",
            "jacques chirac = mangez des pommeschuck norris = mangez des poires et pêches ",
            "on ne dit pas je vais passer un mauvais quart d'heure, mais chuck nurris me cherche ",
            "un jour, james bond a aperçu chuck norris le lendemain, il est devenu boulanger dans le val d'oise ",
            "quand chuck norris roule en twingo, on ne se moque pas de lui ",
            "chuck norris a vu la mort une seule foisavant de la tuer ",
            "c'est chuck norris qui déjoue les plans de minus et cortex ",
            "chuck norris a dépucelé la forêt vierge ",
            "quand chuck norris coupe la queue d'un lézard, elle ne repousse pas ",
            "si la mer se retire, c'est parce que chuck norris arrive ",
            "chuck norris n'est jamais mort, même dans ses vies antérieures ",
            "si chuck norris avait été sur le titanic, il aurait tenu les deux morceaux du navire jusqu'à new-york ",
            "chuck norris a appris à pythagore à se servir d'une équerre ",
            "chuck norris ne traverse pas la route, c'est la route qui passe de l'autre coté de chuck norris ",
            "chuck norris a inventé la science pour que les humains cherchent à le comprendre ",
            "chuck norris peut mimer le verbe mimer ",
            "chuck norris a deux gardes du corps en permanence son bras droit et son bras gauche ",
            "chuck norris a inventé l'intelligence ",
            "quand chuck norris sème de l'argent, ça pousse ",
            "quand chuck norris faisait son service militaire, c'était le sergent-instructeur qui récurait les chiottes ",
            "le jour où chuck norris pètera un cable, le monde s'eteindra ",
            "si king kong est parvenu à monter au sommet de l'empire state building, c'est parce que chuck norris le poussait ensuite il l'a descendu ",
            "chuck norris peut se faire la bise ",
            "le monde se divise en deux catégories : chuck norris, et ceux qui voudraient être chuck norris ",
            "au matin du eme jour, chuck norris accorda à dieu un jour de rtt ",
            "bruce lee faisait des têtes au carré chuck norris fait des têtes au cube ",
            "chuck norris a écrit lui-même excellent sur ses copies du bac ",
            "chuck norris a déjà terminé une peine de prison à perpétuité ",
            "chuck norris n'est pas le parrain de la fille de dieudonné ",
            "l'oeil droit de chuck norris est connu sous le nom de google earth ",
            "un jour michael jackson a fait un pied de nez à chuck norris il l'a payé cher ",
            "jésus était l'apprenti-charpentier de chuck norris ",
            "chuck norris sait faire des angles droits avec un compas ",
            "c'est chuck norris qui a donné ses lunettes de soleil à cyclope des x-men ",
            "chuck norris ne connait pas le sens de try again ",
            "les frères lumière ont inventé le cinéma pour que chuck norris puisse faire walker texas ranger ",
            "chuck norris est poli, il dit veuillez m'excuser avant et pardon après t'avoir cassé la gueule ",
            "chuck norris a ouvert la grotte d'ali baba en disant *ouvre toi ou je t'explose* ",
            "ledécembre, chuck norris offre des cadeaux au père noël ",
            "chuck norris a déjà gagné le tour de france",
            "chuck norris peut faire vraiment pleurer les madeleines ",
            "chuck norris n'a pas besoin de donner d'ordre sa devise: je pense donc ça suit ",
            "chuck norris a tellement d'amour propre qu'il n'a pas besoin de se laver ",
            "si on autorise cindy sander à chanter, c'est uniquement parce qu'elle est la nièce de chuck norris ",
            "chuck norris a déjà couru une minute en moins de soixante secondes ",
            "chuck norris peut appuyer sur alt+maj+suppr en même temps et avec un seul doigt ",
            "quand chuck norris tombe sur une erreur critique sous windows, le son activé est doux, harmonieux, calme et apaisant ",
            "chuck norris ne joue pas à dragon-ball z sur console, il s'insère dans le jeu, ca va plus vite ",
            "quand la rue avance sous chuck norris les crottes de chien s'écartent et même s'excusent",
            "quand chuck norris marche pieds nus, les meubles ne le frappent pas ",
            " chuck norris ",
            "quand chuck norris utilise un biccouleurs, lescouleurs marchent ",
            "quand chuck norris touche du bois, c'est le bois qui a de la chance ",
            "un jour chuck norris à garé son pick-up devant le garage d'un immeuble l'immeuble a été emmené à la fourrière ",
            "quand chuck norris a appris à conduire, il n'avait pas un a derrière son pick-up mais un m pour master ",
            "prométhée a donné le feu aux hommes mais chuck norris l'a breveté ",
            "le prochain épisode des aventures de jason bourn s'intitulera chuck norris dans la peau ",
            "chuck norris a déjà trouvé un uzi dans un kinder surprise ",
            "chuck norris peut compresser l'eau ",
            "chuck norris sait ce qui se passera si l'on jette un chat avec une tartine sur le dos ",
            "chuck norris a enfermé la boule dans les prisons de fort boyard ",
            "chuck norris n'aime pas les nombres impaires, c'est pour ça qu'il a :-tué atchoum (desnains de blanche neige)-fait péter la ième merveille du monde (la ième c'est lui)-il a tué leième mousquetaire-il a bouffé lespetits cochons ",
            "les impôts ne prennent pas d'argent à chuck norris, chuck norris fait un don ",
            "djibril cissé a les pieds carrés depuis que chuck norris les lui a massés ",
            "le proverbe dit: dans la vie, tout vient à point à qui sait attendrechuck norris dit: dans ta gueule, te vient mon poing, que tu t'y attendes ou non ",
            "depuis chuck norris dieu est devenu mortel ",
            "le tapis volant d'alladin est en fait le paillasson de chuck norris ",
            "ribery est la dernière personne à avoir fait la bise à chuck norris ",
            "depuis que chuck norris c'est battu avec jeanne d'arc, elle entend des voix ",
            "la vénus de milo est la derniere personne a avoir fait qui c'est?? à chuck norris ",
            "chuck norris trouve de l'or dans les flaques d'eau ",
            "quand chuck norris boit du coca, la bouteille ne dort pas de la nuit ",
            "un jour une taupe bouscula chuck norris depuis elles n'osent plus se montrer ",
            "chuck norris n'utilise que la carte du ciel sur son gps ",
            "chuck norris peut vous mettre des étoiles dans les yeuxmais attention c'est douloureux ",
            "chuck norris a arrêté l'athlétisme: il en avait marre d'attendre que les autres finissent la course ",
            "si tu tiens tête à chuck norris, il risque de tenir la tienne ",
            "ensemble tout devient possible (mais chuck norris peut déjà le faire tout seul) ",
            "chuck norris aimait bien l'école sinon elle n'existerait plus ",
            "chuck norris a interdit aux volcans d'auvergne d'entrer en éruption ",
            "un cafard peut survivre à une explosion nucléaire mais pas à chuck norris ",
            "les ouragans servent à raffraichir chuck norris ",
            "steven seagal est une groupie de chuck norris ",
            "chuck norris a déjà fait rire mr spock ",
            "les nuls s'appelent ainsi car ils ont eu un jour le malheur de se comparer à chuck norris ",
            "saddam hussein croyait pouvoir battre chuck norris au jeu du pendu ",
            "un jour, chuck norris a tiré vin diesel par les cheveux ",
            "c'est chuck norris qui a inventé la machine à courber les bananes ",
            "sitting bull s'appelait standing bull avant de rencontrer chuck norris ",
            "chuck norris est l'acupuncteur de hell raiser ",
            "il n'y aura jamais chuck norris contre les lapins crétins ils sont crétins, pas fous ",
            "chuck norris ne respire pas l'air ne le mérite pas ",
            "a sa naissance, ce n'est pas la maman de chuck norris qui a poussé, c'est chuck norris qui a tiré ",
            "chuck norris perfectionne ses plongeons dans les chutes du niagara ",
            "chuck norris peut vraiment taper la discute et de la main gauche ",
            "chuck norris a déjà utilisé le gros trou du taille crayon ",
            "le seul endroit où chuck norris se fait des bosses, c'est au ski ",
            "un jour quelqu'un a osé dit non à chuck norris ainsi naquit l'histoire du con qui dit non",
            "chuck norris n'a jamais eu besoin de ceinture noire, son pantalon tient tout seul ",
            "la suite de bienvenue chez les ch'tis sera plus orientée vers l'action le titre sera bienvenue chez chuck norris ",
            "hulk est vert de peur face à chuck norris ",
            "une barre a clous: $un couteau: $un fusil: $un roundhouse-kick de chuck norris: ça n'a pas de prix ",
            "si chuck norris avait joué dans la guerre des boutons, le film se serait appelé la guerre des organes vitaux ",
            "chuck norris imite nicolas canteloup ",
            "depuis que chuck norris a botté le cul de l'angleterre, elle s'est détachée de l'europe ",
            "chuck norris sait lire sur les lèvres mais il préfère quand même lire dans les pensées ",
            "quand chuck norris voit une hirondelle c'est forcément le printemps même quand il neige ",
            "chuck norris peut avoir les yeux partout",
            "chuck norris peut expulser un joueur au babyfoot ",
            "celui qui trouve comment chuck norris est apparu sur terre aura percé le mystere de la vie ",
            "chuck norris a déjà ramassé tous les boyards de la salle du trésor de fort boyard ",
            "au poker, chuck norris peut avoir un quinte d'as ",
            "tant qu'il y a de la viec'est que chuck norris n'est pas passé par ici ",
            "chuck norris trouve encore des lucioles fluos dans ses paquets de bonux ",
            "quand chuck norris va au restaurant, c'est le restaurant qui doit réserver ",
            "un jour chuck norris a uriné dans du café le coca cola était né ",
            "estelle denis a dit non à domenech : elle attend la demande de chuck norris ",
            "de la lune on peut voir la muraille de chine, sauf si chuck norris est assis dessus ",
            "pour arrêter la ségrégation, martin luther king aurait dû dire : i have chuck norris ",
            "chuck norris est le mot de passe de la nasa ",
            "chuck norris peut faire ctrl+alt+suppr avec deux doigts ",
            "chuck norris sait toujours où donner de la têteou du poingou du pied ",
            "un t-shirt chuck norris est plus efficace que n'importe quel gilet pare-balles ",
            "au fond chuck norris ne s'est jamais battu : l'autre n'a jamais eu le temps de répliquer ",
            "chuck norris peut vraiment faire du pop-corn avec son portable ",
            "a la maternelle, c'est la maitresse de chuck norris qui faisait la sieste ",
            "le virus de la rage s'est propagé quand chuck norris a caressé un chien ",
            "quand chuck norris te pique ton yop, tu ne le réclames pas, tu lui proposes d'aller lui en acheter un autre ",
            "chuck norris s'est masturbé la première fois dans le ventre de sa mère c'est ainsi qu'elle tomba enceinte de chuck norris ",
            "la dernière fois que chuck norris a joué a call of duty, c'était deà",
            "qu'aurait dit chuck norris à la place de jésus christ juste avant de mourir ?- vite un autre clou, p de m je glisse ",
            "chuck norris comprend le coaching de domenech ",
            "si des logiciels sont libres, c'est parce que chuck norris les a libérés ",
            "chuck norris ne poste pas sur vdm, la vie de chuck norris n'est pas de la merde ",
            "le meilleur moyen d'avoir un train sncf à l'heure, c'est de voyager avec chuck norris ",
            "chuck norris a fabriqué lui-même son pick-up : on appelé ça l'immatriculée conception ",
            "c'est en jouant avec des légos que chuck norris façonna la terre ",
            "chuck norris est le seul à être capable de créér un dossier nommé con sous windows ",
            "les enfants de chuck norris ne dépassent pas quand ils font du coloriage ",
            "quand chuck norris pète un bras, la victime lui demande un autographe sur le platre ",
            "quand chuck norris fait une mise au poker, le croupier se couche ",
            "chuck norris a déjà bu la tasse: il avait trop soif ",
            "chuck norris est la seule personne qui se moque du caleçon de hulk ",
            "le pick-up de chuck norris est aussi un transformer : il se transforme en chuck norris ",
            "après la pluie, chuck norris ",
            "jésus fut crucifié pour servir de cadran solaire a chuck norris ",
            "l'inventeur du sécateur est un usurpateur, c'était le coupe ongles de chuck norris ",
            "les oiseaux nettoyent le pare-brise du pick-up de chuck norris ",
            "chuck norris a déja pédalé dans la semoule ",
            "chuck norris peut te tuer avec son petit orteil ",
            "chuck norris peut envoyer un texto par la pensée ",
            "tous les policiers ont une photo de chuck norris dans leur casier ",
            "chuck norris s'est deja posé sur le soleil, la nuit ",
            "si chuck norris n'a pas d'ipod, c'est parce qu'il ne dit jamais aïe ",
            "zidane s'est fait mal au crane le jour où chuck norris a parlé de sa soeur ",
            "kenny est la victime favorite de chuck norris ",
            "quand chuck norris fait un barbecue, il ne pleut pas ",
            "chuck norris est la cause des marées, ou plus exactement c'est sa respiration ",
            "quand chuck norris crie une insulte en montagne, il n'y a pas d'écho prudentes, les montagnes, prudentes ",
            "quand alain delon parle de lui à la troisième personne, il parle en fait de chuck norris ",
            "le symbole sur la tunique de sangoku signifie chuck norris, prêtes-moi ta force ",
            "c'est chuck norris qui expédie tous les spam ",
            "quand chuck norris utilise un paint ball, c'est une vraie balle qui sort ",
            "quand chuck norris joue à civilization, il débute avec un colon et l'arme nucléaire ",
            "quand chuck norris fait une division, il n'y a jamais de reste ",
            "quand chuck norris se connecte sur emule, il reçoit sans envoyer chuck norris ne partage avec personne ",
            "le dodo a disparut un matin où chuck norris se réveilla en déclarant ne plus avoir sommeil ",
            "quand chuck norris arrose guizmo, il ne se passe rien ",
            "avant d'aller à l'école, chuck norris déposait ses parents au travail ",
            "si chuck norris saigne, c'est parce qu'il avait trop de sang ",
            "quand chuck norris fume à la fenêtre, la fumée ne rentre jamais à l'intérieur ",
            "chuck norris peut jouer seul au base-ball ",
            "chuck norris n'a pas eu besoin de permis de tuer pour s'occuper de james bond ",
            "devinette : qu'est ce qui est blanc et qui se cache derrière chuck norris ?- le mont everest ",
            "chuck norris a terminé final fantasy vii sans sauvegarder ",
            "chuck norris s'est opéré lui-même de l'appendicitefois ",
            "chuck norris retombe toujours sur ses pattes ",
            "même s'il porte des pin's, chuck norris n'est pas ringard ",
            "chuck norris a fait loucher un cyclope ",
            "quand narcisse s'est regardé dans l'eau, il a vu chuck norris par dessus son épaule ",
            "une fois chuck norris à pris les sept nains en photos et bizarrement:grincheux souriaitsimplet paraissait intelligentprof n'a cassé les couilles à personne sur la manière de se positionnerjoyeux paraissait moins grosatchoum n'a pas voulu éternuertimide ne s'était pas dérobé sous la jupe de blanche-neigedormeur avait les yeux ouvertet blanche-neige avait accepté de poser nue",
            "les atomes qui constituent chuck norris ne sont pas répertoriés par le tableau périodique des éléments ",
            "quand il pleut, chuck norris creuse un tunnel pour ne pas se mouiller ",
            "quand chuck norris commande une pizza, la pizzeria se déplace ",
            "le dernier mec qui avais un cheveux sur la langue et a dit fuck norris n'a toujours pas donné signe de vie ",
            "on peut tromper mille fois mille personnes, mais on ne peut pas tromper chuck norris ",
            "l'onu a prévu un doublement de la population mondiale d'ici % seront des enfants de chuck norris ",
            "quand tu joues au paintball contre chuck norris tu es obligé de prendre un bazooka mais en général tu perds quand même ",
            "chuck norris a déjà doublé la lumière ",
            "quand chuck norris ne voit pas la crotte de chien, quelq'un marche dedans à sa place ",
            "chuck norris a inventé le sel ",
            "si grand-mère fait un bon café, c'est parce que c'est la grand-mère de chuck norris ",
            "tom sawyer n'a peur de rien, normal chuck norris est aussi américain ",
            "depuis que mme de fontenay s'est moquée de la coiffure de chuck norris, elle est obligée de porter un chapeau ",
            "chuck norris n'a pas joué dans 'astérix aux jeux olympiques' ",
            "quand chuck norris veut un déca, il dit à la caféine de se barrer de sa tasse ",
            "la guerre froide s'est terminée quand chuck norris a monté le chauffage ",
            "chuck norris a battu kasparov aux échecs encoups:coups de pied etcoup de boule ",
            "chuck norris est un grand sentimental, il a toujours un cur sur la main ",
            "en plus des codes de lancement des missiles nucléaires, le président de la république reçoit, le numéro du portable de chuck norris on ne sait jamais ",
            "chuck norris a assuré tous les effets spéciaux de cloverfield ",
            "tous les soirs, chuck norris descend ses poubelles a coups de fusil ",
            "_ que vous avez de grandes jambes chuck norris _ c'est pour mieux te foutre un roundhouse kick dans la gueule mon enfant",
            "chuck norris s'est déjà servi du côté bleu de la gomme ",
            "chuck norris n'a pas besoin d'éviter les balles : elles passent à coté le plus discretement possible ",
            "chuck norris peut faire tilter un baby-foot ",
            "chuck norris ne met pas d'essence dans sa voiture, il souffle dans le reservoir ",
            "les vieilles donnent du pain aux pigeons chuck norris donne des pains a tout le monde ",
            "quand chuck norris à six étoiles dans gta, les policiers quittent la ville ",
            "chuck norris peut te tuer avec un cure-dent sans utiliser les pointes ",
            "un jour, chuck norris parti en laissant son verre plein lors d'une soirée arrosée ainsi naquit le saint grâal ",
            "chuck norris n'a jamais joué à saute-mouton personne ne saute chuck norris ",
            "chuck norris déshabille du regard vraiment ",
            "chuck norris fait toujours l'appoing ",
            "chuck norris n'écoute pas de la musique, c'est la musique qui l'écoute elle a intérêt ",
            "quand chuck norris arrive chez les ch'tis ce sont eux qui pleurent ",
            "lorsque l'on fixe trop longtemps chuck norris des yeux, on finit par devenir aveugle c'est ce qui est arrivé à daredevil ",
            "le big bang fut le premier coup de poing de chuck norris etant petit, il avait du mal à controler sa force ",
            "depuis que chuck norris a démontré tous les axiomes, les mathématiciens se sont mis aux arts martiaux ",
            "le pape paye un loyer à chuck norris ",
            "chuck norris a remporté le tournoi mondial d'escrime avec un couteau suisse ",
            "a halloween les enfants qui se déguisent en chuck norris et qui demandent des bonbons chez les voisins repartent avec les bonbons, la carte de crédit, les clefs de la voiture et la femme du voisin ",
            "le chainon manquant sert de menottes à chuck norris dans walker texas ranger ",
            "chuck norris n'a pas d'ampoule chez lui: chuck est une lumière ",
            "chuck norris peut faire diminuer le prix du baril de pétrole ",
            "si chuck norris avait été belge, coluche aurait fait plus de blagues sur les suisses ",
            "chuck norris a inventé l'invention ",
            "quand chuck norris part en vacances, l'onu est en crise ",
            "chuck norris devait être le nouveau messie, mais on a toujours pas réussi à lui clouer les mains ",
            "quand chuck norris cherche des champignons, ils sautent directement dans son panier ",
            "quand chuck norris a le tournis, la terre préfère arrêter de tourner ",
            "chuck norris avait déjà un bac+ avant meme d'avoir le bac ",
            "chuck norris est le seul nom propre que l'on peut jouer au scrabble ",
            "chuck norris est la seule star à posséder une maison sur une plage privée corse les corses préfèrent ne pas y toucher ",
            "le secret de la richesse de bill gates? une photo dédicacée de chuck norris mise aux enchères "
    );

    public static String WELCOME_MESSAGE = "Bienvenue sur le skill de facts sur chuck norris ! Tu peut me demander de te raconter une fact sur lui !";

    // This is the message a user will hear when they try to cancel or stop the
    // skill, or when they finish a fact.
    public static String EXIT_SKILL_MESSAGE = "Merci de m'avoir consulté, à bientôt !";

    // This is the message a user will hear after they chucknorris (and hear) about a
    // specific data element.
    public static String REPROMPT_MESSAGE = "Tu voudrais que je te raconte un fact sur chuck norris ?";

    // This is the message a user will hear when they chucknorris Alexa for help in your
    // skill.
    public static String HELP_MESSAGE = "Je connais beaucoup de facts sur chuck norris ! Tu veut que je t'en raconte une ?";
}
